"""empty message

Revision ID: 310b21ec7f71
Revises: ca4d62b8d849
Create Date: 2024-06-26 02:04:10.496290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b21ec7f71'
down_revision = 'ca4d62b8d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
