"""New Tables

Revision ID: 332019511e18
Revises: b377b15bc74b
Create Date: 2024-06-18 18:19:25.839837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332019511e18'
down_revision = 'b377b15bc74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('sessions',
    sa.Column('ssid', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('referer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ssid')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['permission.role'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_email'))

    op.drop_table('account')
    op.drop_table('sessions')
    op.drop_table('permission')
    # ### end Alembic commands ###
