"""empty message

Revision ID: 50daff1af7a9
Revises: 625f10848a0f
Create Date: 2024-07-06 00:45:08.232085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50daff1af7a9'
down_revision = '625f10848a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
