"""empty message

Revision ID: 8303dee0a59c
Revises: c9c77c0dce8e
Create Date: 2024-07-05 17:12:16.782493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8303dee0a59c'
down_revision = 'c9c77c0dce8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('otp',
    sa.Column('otp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_generated_at', sa.DateTime(), nullable=True),
    sa.Column('otp_secret_key', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('otp_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('failed_attempts')
        batch_op.drop_column('otp_secret_key')
        batch_op.drop_column('otp')
        batch_op.drop_column('lockout_time')
        batch_op.drop_column('login_count')
        batch_op.drop_column('new_email')
        batch_op.drop_column('otp_generated_at')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('new_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lockout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_secret_key', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('otp')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
