"""empty message

Revision ID: 85522884c165
Revises: 648c97d2003a
Create Date: 2024-07-06 02:44:12.355139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85522884c165'
down_revision = '648c97d2003a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('category')
    # ### end Alembic commands ###
