"""empty message

Revision ID: 940413baad3a
Revises: e754be3f8ca9
Create Date: 2024-06-26 01:26:15.468785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '940413baad3a'
down_revision = 'e754be3f8ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('user_fs_uniquifier_key', type_='unique')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('active')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_login_ip', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_fs_uniquifier_key', ['fs_uniquifier'])
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_authenticated')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
