"""empty message

Revision ID: bb363c3c0dd1
Revises: dc04995306d1
Create Date: 2024-07-03 21:05:05.783515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb363c3c0dd1'
down_revision = 'dc04995306d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_email_sent_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('twofa_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twofa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('confirmation_email_sent_at')

    # ### end Alembic commands ###
