"""empty message

Revision ID: c9c77c0dce8e
Revises: 6c3808336908
Create Date: 2024-07-05 15:44:58.288541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9c77c0dce8e'
down_revision = '6c3808336908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testsqlinjection')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret_key', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('otp_secret_key')

    op.create_table('testsqlinjection',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='testsqlinjection_pkey')
    )
    # ### end Alembic commands ###
