"""empty message

Revision ID: ca4d62b8d849
Revises: 940413baad3a
Create Date: 2024-06-26 02:02:27.033782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4d62b8d849'
down_revision = '940413baad3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
