"""empty message

Revision ID: dc04995306d1
Revises: cf2975fbab4b
Create Date: 2024-07-03 11:13:39.544157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc04995306d1'
down_revision = 'cf2975fbab4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('failed_attempts',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('failed_attempts',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
