"""Add credit card information fields to Payment model

Revision ID: dcb51cb4503a
Revises: f32678dfd2e9
Create Date: 2024-07-07 21:09:23.574176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb51cb4503a'
down_revision = 'f32678dfd2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_number', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('cvv', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('cvv')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('credit_card_number')

    # ### end Alembic commands ###
