version: '3.7'

services:
  jenkins:
    image: myjenkins-blueocean:2.452.2-1
    container_name: jenkins-blueocean
    restart: on-failure
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - jenkins

networks:
  jenkins:
    external: true

volumes:
  jenkins_home:
  jenkins-docker-certs:
