version: '3.7'

services:
  react-flask-app:
    build:
      context: $CUSTOM_WORKSPACE/react-flask-app
      dockerfile: Dockerfile
      args:
        - ENV_FILE=server/.env
    container_name: react-flask-app
    environment:
      - VIRTUAL_HOST=forteam22ict.xyz
      - VIRTUAL_PORT=5000
    expose:
      - "3000"
      - "5000"
    networks:
      - jenkins

networks:
  jenkins:
    external: true
