version: '3.7'

services:
  react-flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-flask-app
    environment:
      - VIRTUAL_HOST=forteam22ict.xyz
      - VIRTUAL_PORT=3000
    volumes:
      - .:/usr/src/app
    expose:
      - "3000"
      - "5000"

volumes:
  jenkins_home:
