version: '3.7'

services:
  react-flask-app:
    build:
      context: $WORKSPACE/react-flask-app
      dockerfile: Dockerfile
    container_name: react-flask-app
    environment:
      - VIRTUAL_HOST=forteam22ict.xyz
      - VIRTUAL_PORT=3000
    volumes:
      - $WORKSPACE/react-flask-app:/usr/src/app
    expose:
      - "3000"
      - "5000"
    networks:
          - jenkins

networks:
  jenkins:
    external: true
volumes:
  jenkins_home:
