version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/student24/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/student24/nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt/live/forteam22ict.xyz/fullchain.pem:/etc/ssl/certs/forteam22ict.xyz-fullchain.pem:ro
      - /etc/letsencrypt/live/forteam22ict.xyz/privkey.pem:/etc/ssl/private/forteam22ict.xyz-privkey.pem:ro
      - /etc/letsencrypt/live/jenkins.forteam22ict.xyz/fullchain.pem:/etc/ssl/certs/jenkins.forteam22ict.xyz-fullchain.pem:ro
      - /etc/letsencrypt/live/jenkins.forteam22ict.xyz/privkey.pem:/etc/ssl/private/jenkins.forteam22ict.xyz-privkey.pem:ro
    environment:
      - DEFAULT_HOST=forteam22ict.xyz

  react-flask-app:
    build:
      context: $WORKSPACE/react-flask-app
      dockerfile: Dockerfile
    container_name: react-flask-app
    environment:
      - VIRTUAL_HOST=forteam22ict.xyz
      - VIRTUAL_PORT=3000
    volumes:
      - $WORKSPACE/react-flask-app:/usr/src/app
    expose:
      - "3000"
      - "5000"

volumes:
  jenkins_home:
